name: DarkTPA
version: 1.0
main: jamie.tpa.darksmp.TPALOADER
api-version: 1.20
commands:
  tpa:
    description: Request to teleport to a player
    usage: /<command> <player>
  tpaccept:
    description: Accept a teleport request
    usage: /<command>
  tpdeny:
    description: Deny a teleport request
    usage: /<command> <player>
  tpahere:
    description: Ask a player to teleport to you
    usage: /<command> <player>
  tpaswap:
    description: Swap positions with a player
    usage: /<command> <player>
  darktpa:
    description: DarkTPA plugin command
    usage: /darktpa reload

